apiVersion: apps/v1
kind: Deployment
metadata:
  name: redacre-backend-deployment
  namespace: redacre-interview-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redacre-app
      type: backend
  template:
    metadata:
      labels:
        app: redacre-app
        type: backend
    spec:
      containers:
      - name: redacre-backend
        image: ra-backend:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "100Mi"
            cpu: "50m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: redacre-interview-testing
spec:
  type: ClusterIP
  selector:
    app: redacre-app
    type: backend
  ports:
  - port: 5000
    targetPort: 5000


---
# Frontend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redacre-frontend-deployment
  namespace: redacre-interview-testing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redacre-app
      type: frontend
  template:
    metadata:
      labels:
        app: redacre-app
        type: frontend
    spec:
      containers:
      - name: redacre-frontend
        image: ra-frontend:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "100Mi"
            cpu: "50m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: redacre-interview-testing
spec:
  type: ClusterIP
  selector:
    app: redacre-app
    type: frontend
  ports:
  - port: 3000
    targetPort: 3000


---
# haproxy pod 
apiVersion: v1
kind: Pod
metadata:
  name: redacre-haproxy
  namespace: redacre-interview-testing
  labels:
    name: redacre-haproxy
    type: loadbalancer
spec:
  containers:
  - name: redacre-haproxy
    image: haproxy:custom
    imagePullPolicy: IfNotPresent
    env:
      - name: FRONTEND_SERVERS
        value: frontend-service.redacre-interview-testing
    resources:
      limits:
        memory: "200Mi"
        cpu: "200m"
    ports:
      - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
  namespace: redacre-interview-testing
spec:
  type: NodePort
  selector:
    app: redacre-app
    type: frontend
  ports:
  - port: 8080
    nodePort: 80
    targetPort: 8080


