apiVersion: apps/v1
kind: Deployment
metadata:
  name: redacre-backend-deployment
  namespace: redacre-interview-testing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redacre-app
      type: backend
  template:
    metadata:
      labels:
        app: redacre-app
        type: backend
    spec:
      containers:
      - name: redacre-backend
        image: ra-backend:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "100Mi"
            cpu: "50m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: redacre-interview-testing
spec:
  type: ClusterIP
  selector:
    app: redacre-app
    type: backend
  ports:
  - port: 5000
    targetPort: 5000


---
# Frontend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redacre-frontend-deployment
  namespace: redacre-interview-testing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redacre-app
      type: frontend
  template:
    metadata:
      labels:
        app: redacre-app
        type: frontend
    spec:
      containers:
      - name: redacre-frontend
        image: ra-frontend:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: redacre-interview-testing
spec:
  type: ClusterIP
  selector:
    app: redacre-app
    type: frontend
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redacre-ingress
  namespace: redacre-interview-testing
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
